### ISSUE TITLE
void GY521 :: setAccelSensitivity (uint8_t as)   _afs problem in function.

### ISSUE THREAD

**Issue by SyberMafia** [RobTillaart/GY521#1]
```c
void GY521::setAccelSensitivity(uint8_t as)
{
  if (as > 3) as = 3;
  uint8_t val = getRegister(GY521_ACCEL_CONFIG);
  val &= 0xE7;
  val |= (as << 3);
  setRegister(GY521_ACCEL_CONFIG, val);
  // calculate conversion factor.
  _raw2g = 16384.0;
  for (uint8_t i = 0; i < _afs; i++) _raw2g *= 0.5;
  _raw2g = 1.0 / _raw2g;
}
```
_afs is zero-defined.
the corrected version should be like this.

```c
void GY521::setAccelSensitivity(uint8_t as)
{
  _afs = as;
  if (_afs > 3) _afs = 3;
  uint8_t val = getRegister(GY521_ACCEL_CONFIG);
  val &= 0xE7;
  val |= (_afs << 3);
  setRegister(GY521_ACCEL_CONFIG, val);
  // calculate conversion factor.
  _raw2g = 16384.0;
  for (uint8_t i = 0; i < _afs; i++) _raw2g *= 0.5;
  _raw2g = 1.0 / _raw2g;
}
```
am I right?

**Comment by RobTillaart** [comment]
Thanks for reporting, I will look into it asap.

**Comment by RobTillaart** [comment]
Good catch,  I will fix it today.

**Comment by RobTillaart** [comment]
@SyberMafia 
Should the library have a conversion for AccelSensitivity    from  0123 ==> 2g, 4g,8g,16g ?
idem from GyroSensititity  01234 => 250, 500, 1000, 2000 dps

imho these are not core but can be useful ...

**Comment by RobTillaart** [comment]
@SyberMafia 
Fixed in development branch, please verify
```cpp
void GY521::setAccelSensitivity(uint8_t as)
{
  _afs = as;
  if (_afs > 3) _afs = 3;
  uint8_t val = getRegister(GY521_ACCEL_CONFIG);
  // no need to write same value
  if (((val >> 3) & 3) != _afs)
  {
    val &= 0xE7;
    val |= (_afs << 3);
    setRegister(GY521_ACCEL_CONFIG, val);
  }
  // calculate conversion factor.
  _raw2g = (1 << _afs) / 16384.0;
}
```

also added new functions + new test sketch test_2.ino
```cpp
  void     setThrottleTime(uint16_t ti )     { _throttleTime = ti; };
  uint16_t getThrottleTime()                 { return _throttleTime; };
  uint8_t  getAccelSensitivity();          // returns 0,1,2,3
  uint8_t  getGyroSensitivity();           // returns 0,1,2,3
```

**Comment by SyberMafia** [comment]
> @SyberMafia
> Fixed in development branch, please verify
> 
> ```c++
> void GY521::setAccelSensitivity(uint8_t as)
> {
>   _afs = as;
>   if (_afs > 3) _afs = 3;
>   uint8_t val = getRegister(GY521_ACCEL_CONFIG);
>   // no need to write same value
>   if (((val >> 3) & 3) != _afs)
>   {
>     val &= 0xE7;
>     val |= (_afs << 3);
>     setRegister(GY521_ACCEL_CONFIG, val);
>   }
>   // calculate conversion factor.
>   _raw2g = (1 << _afs) / 16384.0;
> }
> ```
> 
> also added new functions + new test sketch test_2.ino
> 
> ```c++
>   void     setThrottleTime(uint16_t ti )     { _throttleTime = ti; };
>   uint16_t getThrottleTime()                 { return _throttleTime; };
>   uint8_t  getAccelSensitivity();          // returns 0,1,2,3
>   uint8_t  getGyroSensitivity();           // returns 0,1,2,3
> ```

Good job, working properly.

**Comment by SyberMafia** [comment]
I've realized now.
GY521.cpp
```c
uint8_t GY521::getAccelSensitivity()
{
  uint8_t val = getRegister(GY521_GYRO_CONFIG);     REPLACE --> GY521_ACCEL_CONFIG
  _afs = (val >> 3) & 3;
  return _afs;
}
```

**Comment by RobTillaart** [comment]
Good catch, fixed it.
time to merge!
