### ISSUE TITLE
swire support

### ISSUE THREAD

**Issue by netpipe** [RobTillaart/GY521#27]
https://github.com/netpipe/Arduino-Projects/tree/master/libs/GY521

other than version information it should be the same with swire support. thanks.

**Comment by netpipe** [comment]
oopd forgot this part https://github.com/RobTillaart/GY521/commit/b705d0fd9c53c83e19a56dd4d95b8e387e46d6e3

**Comment by RobTillaart** [comment]
It looks like you did not copy the latest version, at least not for all files.

saw you used **swire** instead of **Wire** 
Can you explain the differences?

**Comment by RobTillaart** [comment]
Had a quick look at the softWire library and it has a pretty clean setup, well done. 

Some things popped my mind 

in the .h file you could use ```#pragma once```  instead of the ifdef .../endif construct.  
Compiler just needs to read one line instead of the whole .h file.

There are some functions like beginTransmission that appear twice, one with and one without parameter.
C++ allows default parameters for functions. 
```cpp
uint8_t beginTransmission(bool shouldstop = true)
```

Several functions are oneliners - you might add the **inline** keyword so the compiler can optimize call stack.
(in fact I hope most compilers will recognize these oneliners themselves)

----

Did you do performance tests with the library?

**Comment by RobTillaart** [comment]
> you are welcome to the changes for the main repo if you like.

If time permits I might (maybe now winter is coming)
unfortunately the libraries are one big repo. I had that too in the past, and it became unmanageable in practice.-

>  I'm glad you kept working on it ...

Yes, I try to keep bugs out of my libs and features and performance in, with 100+ libraries under support issues still come in regularly. Sometimes bugs pop up under specific use, hard to recreate. Especially **Heisenbugs**, they only appear if you do not look, right after a 4 hour debugging session or so.

Coming time I will spend time to visualize CI-build results (under actions) and add support of build process for ESP32.  Especially the latter I expect it will expose some weak code parts. At least this helps to keep code quality at a "certain level" 

Is there functionality missing in the GY521 library for you?
Or any other lib?

**Comment by RobTillaart** [comment]
BTW, are you familiar with https://github.com/Testato/SoftwareWire ?

**Comment by gwnspl** [comment]
> BTW, are you familiar with https://github.com/Testato/SoftwareWire ?

i have used the library previously and it works fine !!
BTW i am the freelancer working on the VR glove (https://github.com/netpipe/HappyHands) as mentioned by @netpipe 
Really interesting project and progress so far is good.

hope to finish by weekend !!

**Comment by netpipe** [comment]
[libraries.zip](https://github.com/RobTillaart/GY521/files/7377373/libraries.zip)

i have this working at 2.3 , going to update it a bit. found that newer swire was giving issues.

**Comment by netpipe** [comment]
[examples.zip](https://github.com/RobTillaart/GY521/files/7377386/examples.zip)

updated examples

**Comment by netpipe** [comment]
[GY521-newestfixed.zip](https://github.com/RobTillaart/GY521/files/7377550/GY521-newestfixed.zip)

**Comment by netpipe** [comment]
if you like i can make a fork and put it all in for you with a pull request ?

**Comment by RobTillaart** [comment]
I need to merge #29 before you should fork as the build-CI is broken and I need to fix that first. 
This PR will also update the **begin()** function to include a **wakeup()** call - see #28

**Comment by RobTillaart** [comment]
Installed the GY521-SWIRE.zip as GY521 library (moved mine) , and my existing code that does not use SWire breaks.
That should not happen.

```
C:\Users\Rob\Desktop\GY521___\examples\GY521_performance\GY521_performance.ino: In function 'void setup()':
GY521_performance:22:3: error: 'Wire' was not declared in this scope
   Wire.begin();
   ^~~~
C:\Users\Rob\Desktop\GY521___\examples\GY521_performance\GY521_performance.ino:22:3: note: suggested alternative: 'SWire'
   Wire.begin();
   ^~~~
   SWire
```

**Comment by mdjavedakhtar** [comment]
With swire you have to replace all instances of wire to swire

**Comment by RobTillaart** [comment]
That is not acceptable as when I have a system with 2 busses, one SWire and one hardware Wire I cannot configure the library to handle both. 

With the dependency injection, giving the right wire object as parameter this does work. 

So you should make your SWire library derived from the TwoWire class and then you can just "inject" it.

**Comment by netpipe** [comment]
i forgot to enable swire in the examples  uncomment the #define swire in the demo

#ifdef SWIRE
  sensor.begin(A3,A4);
#else
  Wire.begin();
#endif

**Comment by RobTillaart** [comment]
> i forgot to enable swire in the examples uncomment the #define swire in the demo

It is not the examples I worry about, it is about the real projects people have made with the library.

**Comment by RobTillaart** [comment]
If you derive swire from TwoWire, you can injcect the dependency runtime. Not only in this library but in many more.
you have written most functions already, so I would propose you investigate that path.

**Comment by RobTillaart** [comment]
I close this issue as I will not integrate the current swire solution in the library.
When an Twowire derived SWire class is available, I might have time to test it.
