### ISSUE TITLE
Invalid data without Reset while initializing the begin

### ISSUE THREAD

**Issue by mdjavedakhtar** [RobTillaart/GY521#28]
whith out the code bellow i am getting invalid data when starting up the sensor
  Wire.write(0x6B);                       //make the reset (place a 0 into the 6B register)
  Wire.write(0x00);
  Wire.endTransmission(true);             //end the transmission

we need to reset the MPU6050 before we set any other register

this is coded in your function bool GY521::wakeup()
we need to call this after begin() before we read() any data.

Please verify and include this Readme if needed !!

**Comment by RobTillaart** [comment]
It is rather late now, will check later this week - I did not encounter this problem yet.

Solution should be to add a **wakeup()** call in **begin()**

**Comment by RobTillaart** [comment]
From Datasheet
![image](https://user-images.githubusercontent.com/462844/137981690-0ed56c22-c411-4049-8a26-90fb0cfcaf07.png)

Problem might be caused by the **SLEEP** or the **CYCLE** bit being set.

Can you read the register and post its content (hex value?)

**Comment by mdjavedakhtar** [comment]
i am using SWire instead of Wire so will do the needed changed and let you know after test latter today

**Comment by mdjavedakhtar** [comment]
> I noticed that in the examples I used a loop around wakeup() That might be a solution if the single wakeup() call is not enough.
> 
> ```c++
>   Wire.begin();
> 
>   delay(100);
>   while (sensor.wakeup() == false)
>   {
>     Serial.print(millis());
>     Serial.println("\tCould not connect to GY521");
>     delay(1000);
>   }
> ```

This works fine.
