### ISSUE TITLE
getting position from distance = acceleration * time

### ISSUE THREAD

**Issue by netpipe** [RobTillaart/GY521#32]
was trying to get some mouse position movement data for the screen trying to get acceleration over time maybe someone knows a trick for this with multiple sensors perhaps ?

[VR_Gloves.zip](https://github.com/RobTillaart/GY521/files/7522941/VR_Gloves.zip)

**Comment by RobTillaart** [comment]
https://www.dummies.com/education/science/physics/how-to-calculate-time-and-distance-from-acceleration-and-velocity/

**Comment by netpipe** [comment]
https://howtomechatronics.com/tutorials/arduino/arduino-and-mpu6050-accelerometer-and-gyroscope-tutorial/

**Comment by RobTillaart** [comment]
Thanks for the link, I cannot explain it better.

**Comment by netpipe** [comment]
turns out its more than that, the angular acceleration is not giving linear acceleration. https://answers.unity.com/questions/1221564/rotate-plane-by-normal-how-to-calculate-new-positi.html might be more this

**Comment by netpipe** [comment]
https://www.youtube.com/watch?v=Li6GyubiEls

**Comment by RobTillaart** [comment]
impressive application!

**Comment by netpipe** [comment]
yes, i could not get your library to work with it yet the z calculation is not ready yet. what ide like is a way to convert the acceleration into linear movement somehow. i might need somekinda gravity finding ai that can help do the calculation. maybe using 2 sensors it could spin like a gyro somehow hehe.
