### ISSUE TITLE
Raw data

### ISSUE THREAD

**Issue by orichienal** [RobTillaart/GY521#34]
hi, 
I thought my board was broken, but if you read out the data manually, I get values back.
Unfortunately, with the test1 example, I only get zeros and short deflections when I move it strongly. only the temperature value works properly.
until I found out that you don't get the raw data but a calculated value.
I then built myself functions that give me the raw value, I think it would be good to add that.
the variables also have the name raw but do not contain the raw data.
I think that would help many and also mention it in the explanation.

otherwise a very good library and i hope this is a good suggestion.
Greetings orichienal

**Comment by RobTillaart** [comment]
Thanks
Can you share your adapted code? 
So i can see if it is easily added?
