### ISSUE TITLE
missing ; in .h file

### ISSUE THREAD

**Issue by KrisKasprzak** [RobTillaart/GY521#5]
See line 38

 bool     isConnected()

missing ;

**Comment by RobTillaart** [comment]
Strange, this should have been catched before pushing. 
Anyway need to fix asap.

**Comment by RobTillaart** [comment]
tagged a new release 0.1.4
Apparently 0.1.3 was never tagged so I assume it was still work in progress that was not finished (properly).
Sorry for the inconvenience
