### ISSUE TITLE
Feature request: API for low-pass filter

### ISSUE THREAD

**Issue by FedericoBusero** [RobTillaart/GY521#51]
Nice library! I just woul like to have a dedicated function to set/get the digital low pass filter mode. Something like setDLPFmode and getDLPFmode.

In the mean time, I will directly get/set the register, but a new function looks nicer.

Thanks!

**Comment by RobTillaart** [comment]
Thanks for the request. 
Will look into it (think) next week

**Comment by RobTillaart** [comment]
>  In the mean time, I will directly get/set the register, but a new function looks nicer.

Do you know the register + bit?

**Comment by RobTillaart** [comment]
OK found it 
![image](https://github.com/RobTillaart/GY521/assets/462844/e1dd66e7-e094-4869-95ea-810daf32f7dc)

**Comment by RobTillaart** [comment]
@FedericoBusero 
Created a develop branch, can you verify it works for you?
