### ISSUE TITLE
calibrate function interpretes gravity as error

### ISSUE THREAD

**Issue by mycosd** [RobTillaart/GY521#58]
Hi again,

In `calibrate` the accelerometer values read are automatically set as error (`axe`,`aye`,`aze`). However if you have the MPU flat on a table then it should read az=1. So now `aze` will be set to 1 even if there is absolutely no error in the MPU.
If you are only interested in relative accelerometer readings, this might be exactly what you would want. But for roll/pitch/yaw calculation which is also based on those measurements you get a lot of noise/drift, and the accelerometer angles become completely unusable.

To reproduce:
1. put MPU flat on the table
2. run calibrate
3. read getAngleX/getAngleY/getAngleZ

Now for comparison:
1. put MPU flat on the table
2. run calibrate
3. set sensor.aze-=1;
3. read getAngleX/getAngleY/getAngleZ

The easiest way I can think of handling this is: The calibrate function itself would need an argument that says, eg. `ORIENTATION_X_IS_DOWN`, `ORIENTATION_Y_IS_DOWN`, `ORIENTATION_Z_IS_DOWN` (this should be default) and then you would subtract 1 from the error which matches with the given orientation.
However, this would limit the calibrate function, to be only allowed to be called when the MPU is perfectly aligned on an axis.

Maik

**Comment by RobTillaart** [comment]
Thanks for this explanation, appreciated

**Comment by RobTillaart** [comment]
(sorry for late reaction, too busy with other things).

You're right the Z should read 1 in case of a flat sensor. 

I like the idea of the parameter to indicate the orientation. 
It should ideally support any angle, so the API should look like:
```cpp
calibrate(x_angle = 0, y_angle = 0);  
```
From these two angles the Z angle and the gravity vector are calculatable.
This gravity vector should be "subtracted" from the error, like the Z = 1 you said but now in 3 dimensions. 

Think that is a step too much for now, first step is to get it right for a flat lying sensor.
(I will have a look at your PR now)

**Comment by RobTillaart** [comment]
Looked at the PR and it made 100% sense, so I merged it into the develop branch.
Thanks again!

Are you OK to be mentioned as I want to give credits where they should be?

**Comment by mycosd** [comment]
> Are you OK to be mentioned as I want to give credits where they should be?
Yeah, why not.

I'll try changing the `calibrate` function as you suggested.

**Comment by RobTillaart** [comment]
A first version with AZE -= 1 and reset of the gyro integration is preferred.  That would give a minimal correct release as reference.

**Comment by RobTillaart** [comment]
@mycosd 
Did you have time to run some tests with the new calibrate function?
results?

**Comment by mycosd** [comment]
> @mycosd Did you have time to run some tests with the new calibrate function? results?

I've been using it in my project, in just X=0, Y=0 orientation. It does the job. Only tested few other orientations when implementing it.

It gets rid of the major drift, however there is still a smaller drift which appears to come from the internal gyro integration (`_gyx`, `_gyy`, `_gyz`).

**Comment by RobTillaart** [comment]
Thanks for the update,

**Comment by RobTillaart** [comment]
> it gets rid of the major drift, however there is still a smaller drift which appears to come from the internal gyro integration

The smaller drift is probably related to https://github.com/RobTillaart/GY521/issues/47

Will merge the new calibrate into develop, and get it into master asap.

**Comment by RobTillaart** [comment]
- Merged into develop
- created a PR for the develop branch.

**Comment by RobTillaart** [comment]
@mycosd 
Engineered the **calibrate()** function a bit
- only sum successful reads, ==> samples counter.
- return false if there are no good reads (zero samples)

**Comment by RobTillaart** [comment]
@mycosd 

Merged the improved calibrate() into master, will release 0.6.1 later today.

In the mean time, I got about 15 new issues (other repos as well) so I need to attend some of them too.
So it will take some time to investigate the drift of the sensor (gyroscope integration) which is possibly related to #47.
