### ISSUE TITLE
Bad results with Teensy 3.2

### ISSUE THREAD

**Issue by KrisKasprzak** [RobTillaart/GY521#6]
Using the library with and Arduino NANO works fine. I'm plotting getAccelX, getAccelY, getAccelZ on a serial plotter and values are as expected (+1 / -1 for gradually changing position.

However, using a teensy 3.2 the same code produces very wrong results. The issue is with how the ints are treated on a 32 bit MCU, easy fix, here's how....

replace any int with int16_t and add the uint16_t to the entire value

_ax = ( ( ((int)Wire.read()) << 8) | Wire.read() );  // ACCEL_XOUT_H  ACCEL_XOUT_L

final code
  _ax = (int16_t)(((int16_t)Wire.read() << 8) | Wire.read()) ; // ACCEL_XOUT_H  ACCEL_XOUT_L
  _ay = (int16_t)(((int16_t)Wire.read() << 8) | Wire.read()) ;  // ACCEL_YOUT_H  ACCEL_YOUT_L
  _az = (int16_t)(((int16_t)Wire.read() << 8) | Wire.read()) ;  // ACCEL_ZOUT_H  ACCEL_ZOUT_L
  // TEMPERATURE
  _temperature = (int16_t)(((int16_t)Wire.read() << 8) | Wire.read()) ;  // TEMP_OUT_H    TEMP_OUT_L
  // GYROSCOPE
  _gx = (int16_t)(((int16_t)Wire.read() << 8) | Wire.read()) ;  // GYRO_XOUT_H   GYRO_XOUT_L
  _gy = (int16_t)(((int16_t)Wire.read() << 8) | Wire.read()) ;  // GYRO_YOUT_H   GYRO_YOUT_L
  _gz = (int16_t)(((int16_t)Wire.read() << 8) | Wire.read()) ; // GYRO_ZOUT_H   GYRO_ZOUT_L

This code works on Arduino NANO and Teensy 3.2

**Comment by RobTillaart** [comment]
Thanks for catching this problem. I will make a pull request asap.

**Comment by RobTillaart** [comment]
Can you please verify that changes in this PR is working properly for you?
- https://github.com/RobTillaart/GY521/tree/teensy

**Comment by RobTillaart** [comment]
@KrisKasprzak 
Do you have time to test?

**Comment by KrisKasprzak** [comment]
I have tested it and it's working with Teensy 3.2. well done.
I think the fix could have been applied to the original library so you would not have to create a special branch. I'm guessing the Arduino DUE is a cortext M3 and may need the fix.
Also you may consider not having a special call for the bit shift part. While it's probably not going to impact performance, there is a price in putting a function on the stack etc.
Thanks again.
 

    On Sunday, October 4, 2020, 05:01:15 AM CDT, Rob Tillaart <notifications@github.com> wrote:  
 
 


@KrisKasprzak
Do you have time to test?
